title: IIME Innovation Space
description: Updates from the NYU IIME Innovation Space

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
 - title: IIME
   url: http://www.med.nyu.edu/iime
 - title: Tags
   url: /tags

social:
   github: iime
   twitter: NYULMC_IIME
   email: greg.dorsainville@nyumc.org

google_analytics: "UA-91515516-1"
