title: IIME Innovation Space
description: Updates from the NYU IIME Innovation Space

url: https://ghobot.github.io/blog
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /:title

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

collections:
  devices:
    output: true

defaults:
  - scope:
      path: ""
      type: devices
    values:
      layout: device_page

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Inventory
   url: /inventory
 - title: Tags
   url: /tags
 - title: Gallery
   url: /gallery
 - title: IIME
   url: http://www.med.nyu.edu/iime
 - title: Cardboard
   url: http://ghobot.github.io/iimecardboard/
 - title: Mobility
   url: http://mobile.iime.cloud/

social:
   github: iime
   twitter: NYULMC_IIME
   email: greg.dorsainville@nyumc.org

google_analytics: "UA-91515516-1"
