title: IIME Innovation Space Blog
description: Updates from the NYU IIME Innovation Space

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ghobot
   twitter: sciencelifeny
   email: greg.dorsainville@nyumc.org

google_analytics: 
